# -*- coding: utf-8 -*-
"""PDFtoSentence

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b004KdeDwrnUUfsxDNLjDjr_UQe2F_rt
"""

!pip install nltk
!pip install pymupdf

import fitz  # PyMuPDF
import nltk
import pandas as pd
from nltk.tokenize import sent_tokenize
nltk.download('punkt')

# Fonction pour extraire les phrases d'un PDF
def extract_text_from_pdf(pdf_path):
    doc = fitz.open(pdf_path)
    text_list = []

    for page_num in range(doc.page_count):
        page = doc[page_num]
        text = page.get_text("text")
        sentences = sent_tokenize(text)
        text_list.extend(sentences)

    doc.close()
    return text_list

# Téléchargez votre fichier PDF et remplacez "mon_fichier.pdf" par le nom de votre fichier
from google.colab import files

uploaded = files.upload()

pdf_path = list(uploaded.keys())[0]

# Extraire les phrases du PDF
phrases_du_livre = extract_text_from_pdf(pdf_path)

# Demander à l'utilisateur de fournir le niveau
niveau_utilisateur = 'B2'

# Créer un DataFrame avec les phrases et le niveau
df = pd.DataFrame({
    'sentence': phrases_du_livre,
    'difficulty': niveau_utilisateur
})

df['sentence'] = df['sentence'].replace('\n', ' ', regex=True).replace('\t', ' ', regex=True).replace('–', '', regex=True)

# Supprimer la première et dernière ligne du DataFrame
df = df.drop(df.index[-1])
df = df.drop(df.index[0])
# Supprimer les lignes contenant ")" ou "(" dans la colonne "Phrases"
df = df[-df['sentence'].str.contains('[\(\)]')]
# Supprimer les lignes ne contenant qu'un seul mot dans la colonne "Phrases"
df = df[df['sentence'].apply(lambda x: len(x.split()) > 2)]
# Réinitialiser l'index du DataFrame
df = df.reset_index(drop=True)

print(df.head())
# Enregistrez le DataFrame dans un fichier CSV
df.to_csv('phrases_et_niveau.csv', index=False)
nom_fichier_csv = f"{pdf_path}_niveau_{niveau_utilisateur}.csv"
df.to_csv(nom_fichier_csv, index=False)

# Affichez le chemin du fichier CSV
print(f"Le fichier CSV a été créé : {nom_fichier_csv}")
# Enregistrez le DataFrame dans un fichier CSV

# Téléchargez le fichier CSV
from google.colab import files
files.download(f'{nom_fichier_csv}')



